language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - FRAMEWORK_VERSION="4.1.*" SKELETON_VERSION="4.1.*"
  - FRAMEWORK_VERSION="4.2.*" SKELETON_VERSION="4.2.*"

install:
  - composer require laravel/framework:${FRAMEWORK_VERSION} --no-update
  - composer require laravel/laravel:${SKELETON_VERSION} --dev --no-update
  - composer install --dev --prefer-dist --no-interaction

script:
  - phpunit --verbose

sudo: false
